
export const INCREMENT = 'INCREMENT';

export const DECREMENT = 'DECREMENT';



export const USER_LOGIN_REQUIRES = 'USER_LOGIN_REQUIRES';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_CREATE_REQUIRES = 'USER_CREATE_REQUIRES';

export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';

export const USER_CREATE_ERROR = 'USER_CREATE_ERROR';


export const USER_DELETE_REQUIRES = 'USER_DELETE_REQUIRES';

export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';

export const USER_DELETE_ERROR = 'USER_DELETE_ERROR';
